SET IDENTITY_INSERT [dbo].[Billet] ON
INSERT INTO [dbo].[Billet] ([Id], [AuteurId], [Commentaires], [DepartementId], [Description], [Etat], [Image], [Titre]) VALUES (1, 2, NULL, 1, N'Je n''arrive plus à me connecter sur internet à partir de mon poste au B414', N'EN COURS', NULL, N'Pas de connexion internet')
INSERT INTO [dbo].[Billet] ([Id], [AuteurId], [Commentaires], [DepartementId], [Description], [Etat], [Image], [Titre]) VALUES (2, 2, NULL, 1, N'Antidote faire crash mon mes documents word', N'NOUVEAU', NULL, N'Problème avec le logiciel Antidote')
INSERT INTO [dbo].[Billet] ([Id], [AuteurId], [Commentaires], [DepartementId], [Description], [Etat], [Image], [Titre]) VALUES (3, 2, NULL, 1, N'Un message s''affiche avec du code. Je ne sais pas quoi faire avec tout ça', N'NOUVEAU', NULL, N'Je ne sais pas programmer')
INSERT INTO [dbo].[Billet] ([Id], [AuteurId], [Commentaires], [DepartementId], [Description], [Etat], [Image], [Titre]) VALUES (4, 2, NULL, 1, N'Je ne sais pas si elle est débranché mais je ne peux plus l''utiliser', N'NOUVEAU', NULL, N'Ma souris ne fonctionne plus')
INSERT INTO [dbo].[Billet] ([Id], [AuteurId], [Commentaires], [DepartementId], [Description], [Etat], [Image], [Titre]) VALUES (5, 3, N'Tire la chasse d''eau', NULL, N'Les toillettes sont bouchées mais que dois-je faire ??', N'NOUVEAU', NULL, N'Toilette bouchée')
INSERT INTO [dbo].[Billet] ([Id], [AuteurId], [Commentaires], [DepartementId], [Description], [Etat], [Image], [Titre]) VALUES (6, 3, NULL, 1, N'Je voulais faire un test sur le nouveau système de gestion d''assistance', N'EN COURS', NULL, N'Test')
INSERT INTO [dbo].[Billet] ([Id], [AuteurId], [Commentaires], [DepartementId], [Description], [Etat], [Image], [Titre]) VALUES (7, 2, NULL, 1, N'J''ai vu le premier test et je veux faire pareil', N'EN COURS', NULL, N'Test - 2')
INSERT INTO [dbo].[Billet] ([Id], [AuteurId], [Commentaires], [DepartementId], [Description], [Etat], [Image], [Titre]) VALUES (8, 3, NULL, 1, N'Ça a l''air vraiment cool comme système', N'EN COURS', NULL, N'Problème avec la beauté des choses')
INSERT INTO [dbo].[Billet] ([Id], [AuteurId], [Commentaires], [DepartementId], [Description], [Etat], [Image], [Titre]) VALUES (9, 3, NULL, 1, N'Mon fichier ne s''ouvre pas dans word', N'NOUVEAU', NULL, N'Problème avec Word')
INSERT INTO [dbo].[Billet] ([Id], [AuteurId], [Commentaires], [DepartementId], [Description], [Etat], [Image], [Titre]) VALUES (10, 3, NULL, 1, N'Un message d''erreur s''affiche à l''ouverture du programme', N'NOUVEAU', NULL, N'Dev C++ ne fonctionne pas')
SET IDENTITY_INSERT [dbo].[Billet] OFF
